### ISSUE TITLE
ERROR: Service 'rpc' failed to build: The command '/bin/sh -c gem install bundler && bundle install

### ISSUE THREAD

**Issue by gitleet** [palkan/any_cable_app#7]
When I did a docker compose up I got this error:

```
ERROR: Service 'rpc' failed to build: The command '/bin/sh -c gem install bundler && bundle install --jobs 20 --retry 5' returned a non-zero code: 5
```

During the build I saw this also:

```
Step 6/14 : RUN npm install -g phantomjs
 ---> Running in 136a4566c5c5
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs/bin/phantomjs

> phantomjs@2.1.7 install /usr/lib/node_modules/phantomjs
> node install.js

Considering PhantomJS found at /usr/bin/phantomjs
Looks like an `npm install -g`
Error checking path, continuing { Error: Cannot find module '/usr/lib/node_modules/phantomjs/lib/location'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at getLocationInLibModuleIfMatching (/usr/lib/node_modules/phantomjs/install.js:332:19)
    at Promise._successFn (/usr/lib/node_modules/phantomjs/install.js:389:28)
    at nextTickCallback (/usr/lib/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'MODULE_NOT_FOUND' }
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /usr/lib/node_modules/phantomjs/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

```

**Comment by palkan** [comment]
Thanks for the report.

Fixed  by https://github.com/anycable/anycable_demo/commit/c0ec5cff5a1774fde3081f4bb5fd564a164fc237

Try to upgrade to the latest master and run `docker-compose up web`.

**Comment by gitleet** [comment]
Note: I had to run a docker-compose run web rake db:migrate

Thanks worked.
